"""Reset and align schema v3

Revision ID: db969978bedf
Revises:
Create Date: 2026-07-02 15:50:33.218463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db969978bedf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_templates'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('name', name=op.f('uq_organizations_name'))
    )
    op.create_table('assessment_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('scoring_rules', sa.JSON(), nullable=False),
    sa.Column('adoption_rules', sa.JSON(), nullable=False),
    sa.Column('recommendation_library', sa.JSON(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.id'], name=op.f('fk_assessment_versions_template_id_assessment_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_versions'))
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('population', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('equipe', sa.String(length=255), nullable=True),
    sa.Column('localisation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_participants_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants')),
    sa.UniqueConstraint('org_id', 'external_id', name='uq_participant_org_external_id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_org_id'), ['org_id'], unique=False)

    op.create_table('use_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('IDEE', 'A_ETUDIER', 'EN_EXPERIMENTATION', 'CONCLUANTE', 'USAGE_RECURRENT', 'DIFFUSEE', name='usagestatus'), nullable=False),
    sa.Column('population', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_use_cases_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_use_cases'))
    )
    with op.batch_alter_table('use_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_use_cases_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SYSADMIN', 'ORGADMIN', 'PROGRAM_MANAGER', 'DIRECTION', 'GESTIONNAIRE', 'REPONDANT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('assessment_version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('hash_salt', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['assessment_version_id'], ['assessment_versions.id'], name=op.f('fk_campaigns_assessment_version_id_assessment_versions')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_campaigns_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_org_id'), ['org_id'], unique=False)

    op.create_table('anonymous_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('population', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=255), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('computed_scores', sa.JSON(), nullable=False),
    sa.Column('adoption_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_anonymous_answers_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_anonymous_answers_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anonymous_answers'))
    )
    with op.batch_alter_table('anonymous_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anonymous_answers_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anonymous_answers_org_id'), ['org_id'], unique=False)

    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('consent_text_version', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('given_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_consents_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_consents_participant_id_participants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_participant_id'), ['participant_id'], unique=False)

    op.create_table('follow_up_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('contact_info', sa.String(length=512), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('is_anonymous_respondent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_follow_up_requests_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_follow_up_requests_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_up_requests'))
    )
    op.create_table('identified_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('computed_scores', sa.JSON(), nullable=False),
    sa.Column('adoption_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_identified_answers_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_identified_answers_org_id_organizations')),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_identified_answers_participant_id_participants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identified_answers')),
    sa.UniqueConstraint('campaign_id', 'participant_id', name='uq_identified_answer')
    )
    with op.batch_alter_table('identified_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identified_answers_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identified_answers_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identified_answers_participant_id'), ['participant_id'], unique=False)

    op.create_table('participation_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('participant_hash', sa.String(length=64), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_participation_statuses_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participation_statuses')),
    sa.UniqueConstraint('campaign_id', 'participant_hash', name='uq_participation_hash')
    )
    with op.batch_alter_table('participation_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participation_statuses_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participation_statuses_participant_hash'), ['participant_hash'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('assessment_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BROUILLON', 'EN_REVISION', 'APPROUVE', 'PUBLIE', name='reportstatus'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('methodology_snapshot', sa.JSON(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('report_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_reports_approved_by_id_users')),
    sa.ForeignKeyConstraint(['assessment_version_id'], ['assessment_versions.id'], name=op.f('fk_reports_assessment_version_id_assessment_versions')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_reports_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_reports_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_org_id'))
        batch_op.drop_index(batch_op.f('ix_reports_campaign_id'))

    op.drop_table('reports')
    with op.batch_alter_table('participation_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participation_statuses_participant_hash'))
        batch_op.drop_index(batch_op.f('ix_participation_statuses_campaign_id'))

    op.drop_table('participation_statuses')
    with op.batch_alter_table('identified_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identified_answers_participant_id'))
        batch_op.drop_index(batch_op.f('ix_identified_answers_org_id'))
        batch_op.drop_index(batch_op.f('ix_identified_answers_campaign_id'))

    op.drop_table('identified_answers')
    op.drop_table('follow_up_requests')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_participant_id'))
        batch_op.drop_index(batch_op.f('ix_consents_campaign_id'))

    op.drop_table('consents')
    with op.batch_alter_table('anonymous_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anonymous_answers_org_id'))
        batch_op.drop_index(batch_op.f('ix_anonymous_answers_campaign_id'))

    op.drop_table('anonymous_answers')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_org_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))

    op.drop_table('users')
    with op.batch_alter_table('use_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_use_cases_org_id'))

    op.drop_table('use_cases')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_org_id'))
        batch_op.drop_index(batch_op.f('ix_participants_external_id'))

    op.drop_table('participants')
    op.drop_table('assessment_versions')
    op.drop_table('organizations')
    op.drop_table('assessment_templates')
    # ### end Alembic commands ###
